version: '3.4'

services:
  clinicaparaiso.api:
    image: ${DOCKER_REGISTRY-}clinicaparaisoapi
    build:
      context: .
      dockerfile: ClinicaParaiso.API/Dockerfile
    ports:
      - '57398:8080'
      - '57399:8081'
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "Strong@123"
    volumes:
    - mssql_data:/var/opt/mssql
    ports:
      - '11433:1433'
    expose:
      - 1433
volumes:
    mssql_data:
        